name: weatherapptesting
description: A weather app built with Flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  http: ^1.2.1
  intl: ^0.17.0
  geolocator: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/animations/sunny.gif
    - assets/animations/rainy.gif
    - assets/animations/night.gif
    - assets/animations/snowy.gif
    - assets/animations/thunderstorm.gif
    - assets/animations/cloudy.gif

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit-SemiBoldItalic.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logowa.png"
